---
dist: bionic

sudo: required

language: python
python: "2.7"

jobs:
  include:
  - name: "Front test"
    env: NODE_TYPE=front
  - name: "WN test"
    env: NODE_TYPE=wn

before_install:
 - sudo apt-get update -qq

addons:
  apt:
    packages:
    - python-pip

install:
  # Check ansible version
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - sudo printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Basic role syntax check
  - sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Basic role check
  - sudo ansible-playbook tests/test.yml -i tests/inventory -e storm_type_of_node=$NODE_TYPE

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/