---

- name: Drop storm Config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items:
    - src: "storm_wn.yaml.j2"
      dest: "/opt/storm/conf/storm.yaml"
      owner: "{{ storm_system_user_name }}"
      group: "{{ storm_system_group_name }}"
      service: ""
    - src: "storm.service.j2"
      dest: "/etc/systemd/system/storm-supervisor.service"
      owner: "root"
      group: "root"
      service: "supervisor"
    - src: "storm.service.j2"
      dest: "/etc/systemd/system/storm-logviewer.service"
      owner: "root"
      group: "root"
      service: "logviewer"
  register: storm_config

- name: Restart {{item}} service 
  systemd:
    state: restarted
    name: "{{ item }}.service"
    daemon_reload: yes
    enabled: yes 
  with_items:
    - storm-logviewer
    - storm-supervisor
  when: storm_config.changed

- name: Start {{item}} service 
  systemd:
    state: started
    name: "{{ item }}.service"
    daemon_reload: yes
    enabled: yes 
  with_items:
    - storm-logviewer
    - storm-supervisor

- name: Open ports in firewalld in RedHat/CentOS
  firewalld:
    port: "6700-6800/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  when: ansible_os_family == "RedHat"
  ignore_errors: yes