- name: Create the system groups
  group:
    name: "{{ zk_system_group_name }}"
    state: present
    system: yes

- name: Create system users
  user:
    name: "{{ zk_system_user_name }}"
    group: "{{ zk_system_group_name }}"
    system: yes
    createhome: no

- name: get Zookeeper
  get_url:
    url: "{{ zk_download_mirror }}/zookeeper-{{ zk_version }}/apache-zookeeper-{{ zk_version }}-bin.tar.gz"
    dest: /tmp/
    owner: "{{ zk_system_user_name }}"
    group: "{{ zk_system_group_name }}"
    timeout: 600

- unarchive:
    src: /tmp/apache-zookeeper-{{ zk_version }}-bin.tar.gz
    dest: /opt
    owner: "{{ zk_system_user_name }}"
    group: "{{ zk_system_group_name }}"
    remote_src: yes

- file:
    src: "/opt/apache-zookeeper-{{ zk_version }}-bin/"
    dest: /opt/zookeeper
    owner: "{{ zk_system_user_name }}"
    group: "{{ zk_system_group_name }}"
    state: link
    remote_src: yes

- name: Copy a new zk conf
  copy:
    src: /opt/zookeeper/conf/zoo_sample.cfg
    dest: /opt/zookeeper/conf/zoo.cfg
    owner: "{{ zk_system_user_name }}"
    group: "{{ zk_system_group_name }}"
    remote_src: yes

- name: Set to disable the AdminServer
  lineinfile:
    path: /opt/zookeeper/conf/zoo.cfg
    line:  admin.enableServer=false

- name: Copy ZK service file
  template:
    dest: /etc/systemd/system/zookeeper.service
    src: zookeeper.service.j2